version: '2'

services:
  db:
    image: mongo
    volumes:
      - representantes-patito-db:/data/db

  web:
    image: codeando-mexico/representantes-patito:development
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    expose:
      - 9292
    environment:
      - RACK_ENV=development

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
      - web
    ports:
      - 2222:80


# Necesitamos crear un volumen que se llame:
#   representantes-patito-db
#
# El volumen tendr치 un dump de la base de datos actual,
# para m치s informaci칩n, checa la secci칩n de
# "como-echarlo-a-andar" en el README.md
volumes:
  representantes-patito-db:
    external: true
